version: '3'

services:
  # Application
  database:
    image: 'bitnami/mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - 'mysql_data:/bitnami/mysql'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
